### ISSUE TITLE
Output as utilities

### ISSUE THREAD

**Issue by pandroid** [bradlc/tailwindcss-fluid#2]
Hey @bradlc, I noticed something else.

Wouldn't it better to set the output of the plugin as utilities?
Now the output is set as component. But the plugin doesn't build components like a button or card.

What do you think?

**Comment by bradlc** [comment]
You are absolutely right! Not sure why I used `addComponents` initially.

`addComponents` has been replaced with `addUtilities` in 0.2.0. Thanks again.
